## Problem 17: QR decomposition

### 17a. using numpy.linalg.qr

In [1]:
import numpy as np

# Define a matrix A for QR decomposition
A = np.array([[5,-2], [-2,8]])

# Perform QR decomposition using numpy.linalg.qr
Q, R = np.linalg.qr(A)

# Print the Q and R matrices
print("Q matrix:")
print(Q)
print("\nR matrix:")
print(R)

# Verify that QR = A
print("\nVerifying QR = A:")
print(np.dot(Q, R))

Q matrix:
[[-0.92847669  0.37139068]
 [ 0.37139068  0.92847669]]

R matrix:
[[-5.38516481  4.82807879]
 [ 0.          6.68503217]]

Verifying QR = A:
[[ 5. -2.]
 [-2.  8.]]


### Using Qr decomposition to get the eigenvalues

In [1]:
import numpy as np

def qr_algorithm(A, max_iterations=1000, tolerance=1e-10):
    n = A.shape[0]
    eigenvalues = np.zeros(n, dtype=complex)
    iterations = 0

    while iterations < max_iterations:
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        eigenvalues = np.diag(A)
        
        # Check for convergence
        if np.max(np.abs(np.diag(R, k=1))) < tolerance:
            break

        iterations += 1

    return eigenvalues, iterations

# Example usage:
A = np.array([[5,-2], [-2,8]])
eigenvalues, iterations = qr_algorithm(A)

print("Eigenvalues:", eigenvalues)
print("Number of iterations:", iterations)
A = np.array([[5,-2], [-2,8]])

Eigenvalues: [9. 4.]
Number of iterations: 32


### Comparing with numpy.linalg.eigh

In [3]:
import numpy as np

# Define a symmetric matrix A
A = np.array([[5,-2], [-2,8]])

# Compute eigenvalues and eigenvectors using numpy.linalg.eigh
eigenvalues, eigenvectors = np.linalg.eigh(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues: [4. 9.]

Eigenvectors:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
