## Problem 19: SVD with time of computation

### 19.a.

In [5]:
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [1,0]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [2.41421356 0.41421356]

U matrix:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

Sigma matrix:
[[2.41421356 0.        ]
 [0.         0.41421356]]

V transpose matrix:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Elapsed Time (seconds): 1.5225694179534912


### 19 b.

In [6]:
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [1,0],[0,1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [2.44948974 1.        ]

U matrix:
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

Sigma matrix:
[[2.44948974 0.        ]
 [0.         1.        ]]

V transpose matrix:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Elapsed Time (seconds): 1.543910026550293


### 19.c.

In [7]:
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [-1,1],[1,1],[2,-1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [3.16227766 2.        ]

U matrix:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

Sigma matrix:
[[3.16227766 0.        ]
 [0.         2.        ]]

V transpose matrix:
[[-1. -0.]
 [-0. -1.]]

Elapsed Time (seconds): 0.0


### 19.d.

In [8]:
import numpy as np
import time

# Define a matrix A
A = np.array([[1,1,0], [-1,0,1],[0,1,-1],[1,1,-1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [2.64575131 1.         1.        ]

U matrix:
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01 -2.17233366e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  9.98489519e-17 -9.01324781e-17  7.55928946e-01]]

Sigma matrix:
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]

V transpose matrix:
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Elapsed Time (seconds): 1.5206146240234375


### 19.e.

In [1]:
import numpy as np
import time

# Define a matrix A
A = np.array([[1,1,0], [-1,0,1],[0,1,-1],[1,1,-1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [2.64575131 1.         1.        ]

U matrix:
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01 -2.17233366e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  9.98489519e-17 -9.01324781e-17  7.55928946e-01]]

Sigma matrix:
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]

V transpose matrix:
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Elapsed Time (seconds): 1.5734999179840088


### 19.f.

In [9]:
import numpy as np
import time

# Define a matrix A
A = np.array([[0,1,1], [0,1,0],[1,1,0],[0,1,0],[1,0,1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)

Singular Values: [2.23606798 1.41421356 1.        ]

U matrix:
[[-5.47722558e-01 -3.90285274e-16 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.81370028e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01  3.18822902e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.39736665e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01  8.16496581e-01 -3.49434877e-16  1.32058463e-01
   4.27271064e-01]]

Sigma matrix:
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]]

V transpose matrix:
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [ 7.07106781e-01  1.95639229e-16 -7.07106781e-01]]

Elapsed Time (seconds): 1.5115020275115967
