In [1]:
# 17. QR decomposition
# 17a. using numpy.linalg.qr
import numpy as np

# Define a matrix A for QR decomposition
A = np.array([[5,-2], [-2,8]])

# Perform QR decomposition using numpy.linalg.qr
Q, R = np.linalg.qr(A)

# Print the Q and R matrices
print("Q matrix:")
print(Q)
print("\nR matrix:")
print(R)

# Verify that QR = A
print("\nVerifying QR = A:")
print(np.dot(Q, R))


Q matrix:
[[-0.92847669  0.37139068]
 [ 0.37139068  0.92847669]]

R matrix:
[[-5.38516481  4.82807879]
 [ 0.          6.68503217]]

Verifying QR = A:
[[ 5. -2.]
 [-2.  8.]]


# using Qr decomposition to get the eigenvalues
import numpy as np

def qr_algorithm(A, max_iterations=1000, tolerance=1e-10):
    n = A.shape[0]
    eigenvalues = np.zeros(n, dtype=complex)
    iterations = 0

    while iterations < max_iterations:
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        eigenvalues = np.diag(A)
        
        # Check for convergence
        if np.max(np.abs(np.diag(R, k=1))) < tolerance:
            break

        iterations += 1

    return eigenvalues, iterations

# Example usage:
A = np.array([[5,-2], [-2,8]])
eigenvalues, iterations = qr_algorithm(A)

print("Eigenvalues:", eigenvalues)
print("Number of iterations:", iterations)
A = np.array([[5,-2], [-2,8]])

In [3]:
# Comparing with numpy.linalg.eigh
import numpy as np

# Define a symmetric matrix A
A = np.array([[5,-2], [-2,8]])

# Compute eigenvalues and eigenvectors using numpy.linalg.eigh
eigenvalues, eigenvectors = np.linalg.eigh(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues: [4. 9.]

Eigenvectors:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]


In [4]:
# 18 Power Method
import numpy as np

def power_iteration(A, max_iterations=1000, tolerance=0.01):
    n = A.shape[0]
    x = np.random.rand(n)  # Random initial guess for eigenvector
    x /= np.linalg.norm(x)  # Normalize the initial guess
    iterations = 0
    eigenvalue_old = 0

    while iterations < max_iterations:
        x_new = np.dot(A, x)
        eigenvalue = np.dot(x, x_new)
        x_new /= np.linalg.norm(x_new)

        if np.abs(eigenvalue - eigenvalue_old) < tolerance:
            break
        
        eigenvalue_old = eigenvalue
        x = x_new
        iterations += 1

    return eigenvalue, x, iterations

# Example usage:
A = np.array([[2,-1,0], [-1,2,-1], [0,-1,2]])  # Example symmetric matrix
eigenvalue, eigenvector, iterations = power_iteration(A)

print("Dominant Eigenvalue:", eigenvalue)
print("Corresponding Eigenvector:", eigenvector)
print("Number of iterations:", iterations)

Dominant Eigenvalue: 3.4120543436603277
Corresponding Eigenvector: [ 0.52724836 -0.70656603  0.471989  ]
Number of iterations: 9


In [5]:
# 19 SVD with time of computation
# 19a.
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [1,0]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)


Singular Values: [2.41421356 0.41421356]

U matrix:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

Sigma matrix:
[[2.41421356 0.        ]
 [0.         0.41421356]]

V transpose matrix:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Elapsed Time (seconds): 1.5225694179534912


In [6]:
# 19 b.
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [1,0],[0,1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)


Singular Values: [2.44948974 1.        ]

U matrix:
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

Sigma matrix:
[[2.44948974 0.        ]
 [0.         1.        ]]

V transpose matrix:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Elapsed Time (seconds): 1.543910026550293


In [7]:
# 19c.
import numpy as np
import time

# Define a matrix A
A = np.array([[2,1], [-1,1],[1,1],[2,-1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)


Singular Values: [3.16227766 2.        ]

U matrix:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

Sigma matrix:
[[3.16227766 0.        ]
 [0.         2.        ]]

V transpose matrix:
[[-1. -0.]
 [-0. -1.]]

Elapsed Time (seconds): 0.0


In [8]:
# 19 d
import numpy as np
import time

# Define a matrix A
A = np.array([[1,1,0], [-1,0,1],[0,1,-1],[1,1,-1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)


Singular Values: [2.64575131 1.         1.        ]

U matrix:
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01 -2.17233366e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  9.98489519e-17 -9.01324781e-17  7.55928946e-01]]

Sigma matrix:
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]

V transpose matrix:
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Elapsed Time (seconds): 1.5206146240234375


In [9]:
# 19.e
import numpy as np
import time

# Define a matrix A
A = np.array([[0,1,1], [0,1,0],[1,1,0],[0,1,0],[1,0,1]])

# Start the timer
start_time = time.time()

# Compute SVD using numpy.linalg.svd
U, s, Vt = np.linalg.svd(A)

# Stop the timer
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Create the Sigma matrix from the singular values s
Sigma = np.diag(s)

# Print the singular values, U, Sigma, and Vt
print("Singular Values:", s)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

# Print the elapsed time
print("\nElapsed Time (seconds):", elapsed_time)


Singular Values: [2.23606798 1.41421356 1.        ]

U matrix:
[[-5.47722558e-01 -3.90285274e-16 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.81370028e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01  3.18822902e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.39736665e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01  8.16496581e-01 -3.49434877e-16  1.32058463e-01
   4.27271064e-01]]

Sigma matrix:
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]]

V transpose matrix:
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [ 7.07106781e-01  1.95639229e-16 -7.07106781e-01]]

Elapsed Time (seconds): 1.5115020275115967
